version: "3.5"

services:
    news-parsing-service:
        build:
            context: "."
            args:
                uid: ${UID}
        container_name: news-parsing-service
        ports:
            - 8080:80
        environment:
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
        volumes:
            - .:/var/www/html
        networks:
            backend:
                aliases:
                    - laraparsing

    laraparsing-db:
        image: mysql:5.7
        container_name: laraparsing-db
        volumes:
            - ./my/data:/var/lib/minesql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            backend:
                aliases:
                    - laraparsing-db

networks:
    backend:
        name: laraparsing-network
